### PR TITLE
Wordlist helper

### PR DESCRIPTION
**Pull request by gigkokman**
Introducing WordList class in wordlist_helper

### CODE REVIEW

**Comment by codingo** [comment]
I'm travelling at the moment and I'm not sure what @timkent's schedule is looking like so it may be a couple of days before we can test/merge this one!

**Comment by gigkokman** [comment]
No problem, let me know if you have any suggestion.

**Comment by codingo** [comment]
Had a chance for a quick look and this is currently failing, results below:

> root@kali:~/source/testing/VHostScan# python ./VHostScan.py -t testbench.home
> +-+-+-+-+-+-+-+-+-+  v. 1.7.1
> |V|H|o|s|t|S|c|a|n|  Developed by @codingo_ & @__timk
> +-+-+-+-+-+-+-+-+-+  https://github.com/codingo/VHostScan
> 
> Traceback (most recent call last):
>   File "./VHostScan.py", line 119, in <module>
>     main()
>   File "./VHostScan.py", line 35, in main
>     wordlist, wordlist_types = wordlist_helper.get_wordlist(arguments.wordlist)
> AttributeError: 'Namespace' object has no attribute 'wordlist'
> 

The following tests should pass:

- STDIN only
- STDIN + wordlist
- No STDIN, default wordlist (no flags, will automatically select)
- No STDIN, provided wordlist

**Comment by codingo** [comment]
Sorry @gigkokman - there's one bug that was introduced with this. It looks like when you do a pipe it's now appending the default wordlist (when data is passed in pipe it should be treated as if it's the only data).

When you do the following:

`echo "test" | python ./VHostScan.py -t <target> --no-lookups
`
You should only see a result for test. At the moment it appends the full default wordlist onto this also.

**Comment by gigkokman** [comment]
Thanks @codingo, I'll fix and recheck again.

**Comment by codingo** [comment]
Thank-you @gigkokman! I'm intending on putting in automated test cases for this in future that will help give more immediate feedback - sorry that wasn't the case prior to this pr.

**Comment by gigkokman** [comment]
@codingo , I add new test case for stdin and wordlist and I think it covers 4 cases above.
Let me know if you have another issue.

**Pull request merged**
