### PR TITLE
Command Line Colours

### PR DESCRIPTION
**Pull request by codingo**
This is the foundation for adding colours to the output of VHostScan as discussed in #47.

### CODE REVIEW

**Comment by maxoja** [comment]
I want to make this happen. Should I create a new pull request?

**Comment by codingo** [comment]
Either is OK. A new one would be best if you're doing hacktoberfest so it properly counts towards your submissions.

**Comment by maxoja** [comment]
> Either is OK. A new one would be best if you're doing hacktoberfest so it properly counts towards your submissions.

I will go ahead and create a new one
Thanks so much

**Comment by maxoja** [comment]
@codingo 
It seems implementing this feature requires a module named `termcolor` which a user has to have it installed first. I suppose that I need to add a specific module name and version in `requirements.txt`. However, I am not confident that it will be all I have to do to update the dependency tree of your program. Anything else I should do?

**Comment by codingo** [comment]
Closing as this is now in #103

**Pull request closed without merging**
