### PR TITLE
Python3 Refactoring (first phase)

### PR DESCRIPTION
**Pull request by linted**
Updates to get the repo closer to python3 standards.

### CODE REVIEW

**Comment by codingo** [comment]
Will review this on Monday. Appreciated change!

**Comment by linted** [comment]
Yeah, fixing the pep8 issues. That was the one think I forgot to check.

**Comment by codingo** [comment]
Just touching base to let you know that I'm not ignoring this. I've received quite a lot of pull requests over a few days (a great problem really!). Hoping to have everything up to date by Wednesday evening, but may not get to this until then.

**Comment by codingo** [comment]
Great changes. Once the code base is more consistent with this I'll enforce it with a new automated test case also.

**Pull request merged**
